import Head from 'next/head'
import NewsPage from '../../src/pages/NewsPage'

export default function Registro() {
  return (
    <div>
      <Head>
        <title>Noticias</title>
        <meta name="description" content="Generated by Jorge Villamizar and Carlota Lasa" />
      </Head>
      <NewsPage />
    </div>
  )
}
