import Head from 'next/head'
import MainPage from '../../src/pages/MainPage'

export default function Registro() {
  return (
    <div className='bg-[#E0E0E0] h-[100vh]'>
      <Head>
        <title>Main</title>
        <meta name="description" content="Generated by Jorge Villamizar and Carlota Lasa" />
      </Head>
      <MainPage />
    </div>
  )
}
