import Head from 'next/head'
import RegisterPage from '../../src/pages/RegisterPage'

export default function Registro() {
  return (
    <div>
      <Head>
        <title>Registrarse</title>
        <meta name="description" content="Generated by Jorge Villamizar and Carlota Lasa" />
      </Head>
      <RegisterPage />
    </div>
  )
}
