import Head from 'next/head'
import AdminPage from '../../src/pages/AdminPage'

export default function Admin() {
  return (
    <div>
      <Head>
        <title>Administrador</title>
        <meta name="description" content="Generated by Jorge Villamizar and Carlota Lasa" />
      </Head>
      <AdminPage />
    </div>
  )
}
