import Head from 'next/head'
import AdminPanelPage from '../../src/pages/AdminPanel'

export default function AdminPanel() {
  return (
    <div>
      <Head>
        <title>Administrador</title>
        <meta name="description" content="Generated by Jorge Villamizar and Carlota Lasa" />
      </Head>
      <AdminPanelPage />
    </div>
  )
}