import Head from 'next/head'
import AdminPanelPage from '../../src/pages/AdminPanel'

export default function AdminPanel(props) {
  return (
    <div>
      <Head>
        <title>Administrador</title>
        <meta name="description" content="Generated by Jorge Villamizar and Carlota Lasa" />
      </Head>
      <AdminPanelPage />
    </div>
  )
}

export async function getServerSideProps(context) {
  return {
    props: {}, // will be passed to the page component as props
  }
}